services:
  postgres:
    image: postgres:13
    container_name: bigdata_hm_02_hive_postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: bigdata_hm_02_hive_metastore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
    ports:
      - "9083:9083"
    volumes:
    - ./data:/data
    platform: linux/amd64

  hive-server:
    image: apache/hive:3.1.3
    container_name: bigdata_hm_02_hive_server
    depends_on:
      - hive-metastore
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_METASTORE_URIS: thrift://hive-metastore:9083
    ports:
      - "10000:10000"
    volumes:
    - ./data:/data
    platform: linux/amd64

volumes:
  pgdata: